### ISSUE TITLE
Comment functionality doesn't work

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-raendom#137]
Chrome 80.0.3

* I've openned a youdonotneedacapetobeahero.com and i have latest wallet extension.
* I've pressed a comment button, it opened a new view, i've entered a comment and got stuck on loader till it disappears.

And my comment did not appear.

**Comment by mradkov** [comment]
Can you elaborate more on this further.

In order to comment you need to have the wallet extension installed.

P.S. Just tried it and it works. Are you experiencing other problems? Provide steps for reproducing.

**Comment by CedrikNikita** [comment]
1) I've openned a youdonotneedacapetobeahero.com and i have latest wallet extension. 
2) I've pressed a comment button, it opened a new view, i've entered a comment and got stuck on loader till it disappears.
3) And my comment did not appear.

**Comment by thepiwo** [comment]
Are there any issues in network monitor or console?

**Comment by CedrikNikita** [comment]
I'm sorry that was a problem with my provider. It's perfectly working through the vpn.
