### ISSUE TITLE
Left panel inconsistencies

### ISSUE THREAD

**Issue by venimus** [aeternity/aepp-raendom#144]
Left navigation panel sizes on higher resolutions (1366+) are inconsistent with design (dimmer bottom layer is the designed) :

1. Logo size
1. Font sizes/weight
1. Offset from the main panel
1. Padding between items
1. Offset of metrics

![image](https://user-images.githubusercontent.com/632282/76832460-059c3c00-6832-11ea-8402-bc9e30483472.png)

Current should stay for mid-res monitors (1024-1366)

**Comment by mradkov** [comment]
Can you make PR for this?
