### ISSUE TITLE
Comments are not displayed in tipview sometimes

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-raendom#166]
![filter](https://user-images.githubusercontent.com/9008074/77050115-fa553600-6a14-11ea-8e72-c0a503eafad0.gif)

**Comment by mradkov** [comment]
Do you want to make a PR to fix this?

**Comment by CedrikNikita** [comment]
Looks like it was fixed by this PR https://github.com/aeternity/aepp-raendom/pull/174
