### ISSUE TITLE
Broken images fallback/display

### ISSUE THREAD

**Issue by venimus** [aeternity/aepp-raendom#189]
![image](https://user-images.githubusercontent.com/632282/77162316-5c18ad00-6ab4-11ea-8e6a-944de8231fb4.png)

**Comment by kenodressel** [comment]
This is an issue with the backend currently as well. You either get no image or a working one. Broken ones should not be possible anymore after i fix this

**Comment by venimus** [comment]
I think there might be network issues or bugs, so it is good to have some fallback.
