### ISSUE TITLE
Left navigation font size inconsistences

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-raendom#213]
The left navigation font size is different on chrome and firefox

<img width="252" alt="Screenshot 2020-03-24 at 9 40 31" src="https://user-images.githubusercontent.com/13139371/77400305-9daaa000-6db3-11ea-8fd9-b820d187dda9.png">
<img width="244" alt="Screenshot 2020-03-24 at 9 40 36" src="https://user-images.githubusercontent.com/13139371/77400309-9e433680-6db3-11ea-8ec9-1f580c3b50d6.png">

**Comment by venimus** [comment]
I think you have different "zoom" or window size. The font is changed <1440

**Comment by mradkov** [comment]
Same device, same screen width - browsers on 100% zoom (just checked).
