### ISSUE TITLE
"Trending" is shown as "active" on home page

### ISSUE THREAD

**Issue by venimus** [aeternity/aepp-raendom#215]
This is because router sets it as "active" because both point to the same route (home)

ref https://github.com/aeternity/aepp-raendom/pull/209/files#diff-8fbe63fdc7f72ebbada18d87c97afefaR15

**Comment by stanislav-slavov** [comment]
Where should "Trending" page point to? If there is no specific location we should probably remove it for now.

**Comment by venimus** [comment]
Not sure what it should be but its state is confusing now

**Comment by mradkov** [comment]
There should be a page for all the trending tags (#101). But until there is design for it it better to point to the home (the tiplist view) with "Most popular" filter I guess.

**Comment by mradkov** [comment]
We should make Home and Trending to not be active at the same time for now. When we have designs and their implementation we'll set it to point to the new page.
