### ISSUE TITLE
Different timestamp types

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-raendom#236]
Comment and tip have different type of timestamp, I suggest to choose one of them.
- tip timestamp type is number: 1584484988877
- comment timestamp type is a String: 2020-03-17 13:09:14.485 +00:00

**Comment by mradkov** [comment]
We cannot modify the timestamp coming from the contract (tip timestamp), so in this case I'd suggest to change the one used in the backend (comments). cc @kenodressel

**Comment by kenodressel** [comment]
We can but I suggest you use `new Date(timestamp/string)` and js should parse both of these with no problems.
