### ISSUE TITLE
Retip did not update view

### ISSUE THREAD

**Issue by kenodressel** [aeternity/aepp-raendom#37]
After retip the number tip total / view did not update

**Comment by davidyuk** [comment]
Seems that I can't reproduce this one. On the `feature/layout-superhero` branch I was trying to retip from tips list and from tip details. In both cases, the tips value for the current post and "Total Tips Value" were updated after several seconds.

**Comment by thepiwo** [comment]
I thinks there needs to be a general loading animation, as tried in https://github.com/aeternity/aepp-raendom/pull/29.

Otherwise I think this issue was reported with old state of the product.
