### ISSUE TITLE
Successful tip view issues

### ISSUE THREAD

**Issue by kenodressel** [aeternity/aepp-raendom#39]
- [ ] Let them know does not work

![image](https://user-images.githubusercontent.com/765921/75761032-9fdf8880-5d38-11ea-8a16-eaf8de4a2e2e.png)

**Comment by davidyuk** [comment]
Is there any idea of how it should work? I don't think that exist some method of notifying the owner of an arbitrary URL, so I propose to make it a plain text in https://github.com/aeternity/superhero-wallet/pull/7

**Comment by mradkov** [comment]
We can make `Let them know` button/link copy the text from the textbox and allow user to paste it somewhere to notify the owner/creator of the URL (via email, chat, social media etc.).

And also display some notification that the text was copied to the clipboard.
