### ISSUE TITLE
Use vue/cli as a boilerplate

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-raendom#42]
They have great hot reloading out of the box, it should increase development speed.

**Comment by thepiwo** [comment]
why would this increase development speed? whats the issues with the current way. Please elaborate.

Also maybe @kenodressel help with a decision. For reference our work in the boilerplate: https://github.com/kenodressel/aepp-boilerplate/pull/7

**Comment by davidyuk** [comment]
Hot reloading allows applying changes of particular components without reloading the whole page. It currently is not enabled in this repo: any small change of a component leads to page reloading. This is more time consuming when the page depends on remote data or some login flow.

I have compared the time that needed to make a change in this app and in the Base aepp (it uses @vue/cli) on my computer. In this app, I was adding random text after title in `TipRecordComponent` looking at the root page, and in the Base app, I was doing the same in `ListItemTransaction` looking at transaction list. Time was measured manually between pressing `ctrl+s` in the editor and showing the necessary changes. I have repeated measurements several times. So, for the Base app it takes about 2 seconds, and for this app about 8 seconds.

**Comment by kenodressel** [comment]
I agree that hot-reloading is a nice feature but the question is
a) is the effort to switch this over to vue-cli worth the time we save?
b) is it possible  to integrate hot-reloading in the current boilerplate (also could be helpful for the aepp-boilerplate repo)

**Comment by davidyuk** [comment]
> is the effort to switch this over to vue-cli worth the time we save?

I think so. Today I have tried to build using @vue/cli (#124) and I didn't face any significant problems while migration.

> is it possible to integrate hot-reloading in the current boilerplate 

For sure it is possible, but it would be more efficient to use webpack configs maintained by vue community.
