### ISSUE TITLE
display more stats in the frontend

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-raendom#52]
- total received
- total spent
- tips received
- tips claimed
- tips unclaimed

- users tipped (?)

**Comment by kenodressel** [comment]
- Participants (eg unique addresses that tipped and or commented)

**Comment by thepiwo** [comment]
- we can't know how much tips have been received without indexing the contract payout events
 - we can't know unclaimed tips at all, oracles decide what is claimable and what is not
